sudo: false
# dist: trusty
language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - check
    - libssl-dev
    - python3-pip
    - valgrind
    - libsodium-dev

env:
  global:
    - PYTHON=python3

install:
  - $PYTHON -m pip install --user pytest ecdsa curve25519-donna

script:
  - make
  - make lib
  - ./tests/aestst
  - ./tests/test_check
  - CK_TIMEOUT_MULTIPLIER=20 valgrind -q --error-exitcode=1 ./tests/test_check
  - ./tests/test_openssl 1000
  - cd ./tests ; ITERS=10 $PYTHON -m pytest ; cd ..

